import {describe,it,expect} from 'vitest';
import {defaults,source,configSchema,parseConfig} from '../config/schema';
import {buildModel,calculate,dimensions,segmentIntersectsBox,type Vec} from '../domain/model';
import {primitives,displacement} from '../geometry/primitives';
import {csvExport,jsonExport,schedule} from '../export/exports';
const config=()=>structuredClone(defaults),baseline=buildModel(config());
describe('supplied electrical invariants',()=>{
 it('calculates the full precision baseline without using rounded source energy',()=>{const s=baseline.stats;for(const [key,value] of Object.entries({cellEnergy:1.0048,packVoltage:332.8,packEnergy:104.4992,packPower:52.2496,cRate:.5,packs:48,cells:4992,energy:5015.9616,power:2507.9808,hours:2,voltage:1331.2,maxVoltage:1518.4,minVoltage:1040,capacity:3768,current:1884}))expect(s[key as keyof typeof s]).toBeCloseTo(value,8);expect(s.packEnergy).not.toBe(source.packEnergyLabel);});
 it('contains exactly 48 packs and 4992 addressable cells with unique IDs',()=>{expect(baseline.packs).toHaveLength(48);expect(baseline.cells).toHaveLength(4992);expect(new Set(baseline.nodes.map(n=>n.id)).size).toBe(baseline.nodes.length);for(const pack of baseline.packs){const cells=baseline.cells.filter(n=>n.parent===pack.id);expect(cells).toHaveLength(104);expect(new Set(cells.map(n=>`${n.row}:${n.column}`)).size).toBe(104);expect(new Set(cells.map(n=>n.row)).size).toBe(8);expect(new Set(cells.map(n=>n.column)).size).toBe(13);}});
 it('forms a single 104-cell polarity-correct path in every pack',()=>{for(const pack of baseline.packs){const edges=baseline.electrical.edges.filter(e=>e.kind==='busbar'&&e.from.startsWith(pack.id+'/C')&&e.to.startsWith(pack.id+'/C'));expect(edges).toHaveLength(103);const next=new Map<string,string>();for(const e of edges){const f=baseline.electrical.ports[e.from],t=baseline.electrical.ports[e.to];expect(f.kind).toBe('positive');expect(t.kind).toBe('negative');expect(next.has(f.node)).toBe(false);next.set(f.node,t.node);}const visited=new Set<string>();let id=`${pack.id}/C001`;while(id){expect(visited.has(id)).toBe(false);visited.add(id);id=next.get(id)!;}expect(visited.size).toBe(104);expect(visited.has(`${pack.id}/C104`)).toBe(true);}});
 it('preserves 48 packs while regenerating all strings in the alternative',()=>{const c=config();c.preset='alternative';const alt=buildModel(c);expect(alt.racks).toHaveLength(16);expect(alt.packs).toHaveLength(48);for(const r of alt.racks){const packs=alt.packs.filter(p=>p.parent===r.id);expect(packs).toHaveLength(3);expect(alt.electrical.edges.filter(e=>e.kind==='hv'&&packs.some(p=>e.from===`${p.id}:+`)&&packs.some(p=>e.to===`${p.id}:-`))).toHaveLength(2);}for(const [key,value] of Object.entries({voltage:998.4,maxVoltage:1138.8,minVoltage:780,capacity:5024,current:2512,energy:5015.9616}))expect(alt.stats[key as keyof typeof alt.stats]).toBeCloseTo(value,8);expect(alt.dimensions.required[0]).toBeGreaterThan(baseline.dimensions.required[0]);expect(alt.warnings.some(w=>w.code==='overvoltage')).toBe(false);expect(alt.warnings.some(w=>w.code==='pcs-review')).toBe(true);});
 it('requires explicit equipment limits and flags overvoltage',()=>{expect(baseline.warnings.some(w=>w.code==='overvoltage')).toBe(true);const c=config();c.equipment.maxVoltage=null;expect(buildModel(c).warnings.some(w=>w.code==='voltage-unknown')).toBe(true);});
 it('flags low-voltage constant-power current and optional AC feasibility',()=>{const c=config();c.usable.constantDCKW=2507.9808;let s=calculate(c);expect(s.currentAtMin).toBeCloseTo(2411.52);expect(buildModel(c).warnings.some(w=>w.code==='constant-current')).toBe(true);expect(s.duration).toBeNull();c.usable={...c.usable,soc:.9,efficiency:.95,auxKW:40,acKW:2000};s=calculate(c);expect(s.duration).toBeCloseTo(5015.9616*.9*.95/2040);expect(buildModel(c).warnings.some(w=>w.code==='ac-current')).toBe(true);});
});
describe('physical geometry and routing',()=>{
 it('keeps cell proportions and body runs exact',()=>{const c=baseline.cells[0];expect(c.size).toEqual([.174,.207,.0717]);expect(baseline.dimensions.body[0]).toBeCloseTo(1.392);expect(baseline.dimensions.body[2]).toBeCloseTo(.9321);[1.419,.253,1.0501].forEach((v,i)=>expect(baseline.dimensions.pack[i]).toBeCloseTo(v,9));});
 it('regenerates dimensions when gaps and cell ranges change',()=>{const c=config();c.assumptions.cellWidth=173.5;c.assumptions.cellGap=5;const d=dimensions(c);expect(d.pack[0]).toBeCloseTo(baseline.dimensions.pack[0]-.004);expect(d.pack[2]).toBeCloseTo(baseline.dimensions.pack[2]+12*.0035);expect(buildModel(c).cells[0].size[0]).toBe(.1735);});
 it('reports insufficient envelope, aisle, connectors and service interference',()=>{const c=config();Object.assign(c.assumptions,{manual:true,length:1000,height:500,width:1000,aisle:600,requiredAisle:900,connector:30,bendRadius:40,endBay:450,rackGap:60});const codes=buildModel(c).warnings.map(w=>w.code);for(const code of ['fit-length','fit-height','fit-width','aisle','connector','service-interference','rack-collision'])expect(codes).toContain(code);});
 it('routes every graph edge to explicit domain ports',()=>{for(const g of [baseline.electrical,baseline.hydraulic])for(const edge of g.edges){expect(edge.points[0]).toEqual(g.ports[edge.from].position);expect(edge.points.at(-1)).toEqual(g.ports[edge.to].position);expect(g.ports[edge.from].kind.startsWith('supply')||g.ports[edge.from].kind.startsWith('return')).toBe(g===baseline.hydraulic);}});
 it('closes supply/return loops through all 48 parallel cold plates',()=>{const g=baseline.hydraulic;for(const pack of baseline.packs){const supply=`${pack.id}:supply`,ret=`${pack.id}:return`;expect(g.edges.some(e=>e.from===`${pack.parent}:supply`&&e.to===supply)).toBe(true);expect(g.edges.some(e=>e.from===supply&&e.to===ret&&e.kind==='coldPlate')).toBe(true);expect(g.edges.some(e=>e.from===ret&&e.to===`${pack.parent}:return`)).toBe(true);}for(const id of Object.keys(g.ports)){expect(g.edges.some(e=>e.from===id)).toBe(true);expect(g.edges.some(e=>e.to===id)).toBe(true);}});
 it('keeps route centerlines outside all cell interiors',()=>{expect(baseline.intersections).toEqual([]);});
 it('keeps the detail view tied to an installed pack and stable instance IDs',()=>{const c=config();c.visibility.busbars=true;const model=buildModel(c),ps=primitives(model,'R01/P01');expect(ps.filter(p=>p.id.endsWith('#body'))).toHaveLength(104);expect(new Set(ps.filter(p=>p.id.endsWith('#body')).map(p=>p.owner)).size).toBe(104);expect(ps.some(p=>p.owner.startsWith('R02'))).toBe(false);expect(model.packs).toHaveLength(48);});
 it('hides routes consistently while exploding and exports assembled positions',()=>{const c=config();c.explode=.8;c.visibility.busbars=true;const model=buildModel(c);expect(primitives(model).some(p=>['hv','busbars'].includes(p.category))).toBe(false);expect(displacement(model.cells[0],model)[1]).toBeGreaterThan(0);const assembled=primitives(model,'BESS',true);expect(assembled.find(p=>p.id==='R01/P01/C001#body')!.position).toEqual(model.cells[0].position);expect(assembled.some(p=>p.category==='hv')).toBe(true);});
});
describe('configuration and schedules',()=>{
 it('round-trips source, assumptions, camera, visibility and graph-derived results',()=>{const c=config();c.assumptions.rowGap=8;c.visibility.earth=true;c.camera.position=[5,7,8];const model=buildModel(c),json=jsonExport(model),restored=parseConfig(json);expect(restored).toEqual(c);expect(buildModel(restored).stats).toEqual(model.stats);expect(JSON.parse(json).topology.electrical.edges).toHaveLength(model.electrical.edges.length);});
 it('rejects malformed, unsupported or unsafe configurations',()=>{expect(()=>parseConfig('{}')).toThrow();expect(configSchema.safeParse({...defaults,version:2}).success).toBe(false);const c=config();c.assumptions.cellGap=-1;expect(configSchema.safeParse(c).success).toBe(false);c.assumptions.cellGap=NaN;expect(configSchema.safeParse(c).success).toBe(false);expect(configSchema.safeParse({...defaults,logo:'javascript:alert(1)'}).success).toBe(false);const j=JSON.parse(jsonExport(baseline));j.source.packEnergyLabel=999;expect(()=>parseConfig(JSON.stringify(j))).toThrow();});
 it('exports exact component totals, stable IDs and no invented ratings',()=>{const rows=schedule(baseline);for(const [kind,quantity] of [['cell',4992],['pack',48],['rack',12]] as const)expect(rows.filter(r=>r[1]===kind).reduce((n,r)=>n+r[2],0)).toBe(quantity);expect(new Set(rows.map(r=>r[0])).size).toBe(rows.length);expect(csvExport(baseline)).toContain('ratings unspecified');});
});

describe('assembled GLB exporter',()=>{
 it('produces valid binary glTF with instance identities and assembled transforms',async()=>{
  class TestFileReader {result:ArrayBuffer|null=null;onloadend:(()=>void)|null=null;readAsArrayBuffer(blob:Blob){blob.arrayBuffer().then(b=>{this.result=b;this.onloadend?.();});}}
  const previous=globalThis.FileReader;globalThis.FileReader=TestFileReader as unknown as typeof FileReader;
  try{const {glbExport}=await import('../export/exports');const c=config();c.explode=1;c.visibility.cells=false;const blob=await glbExport(buildModel(c)),buffer=await blob.arrayBuffer(),view=new DataView(buffer);expect(view.getUint32(0,true)).toBe(0x46546c67);expect(view.getUint32(4,true)).toBe(2);expect(view.getUint32(8,true)).toBe(buffer.byteLength);const jsonLength=view.getUint32(12,true),json=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,20,jsonLength)));const ids=json.nodes.flatMap((n:{extras?:{instanceIds?:string[]}})=>n.extras?.instanceIds??[]);expect(ids.filter((id:string)=>/C\d{3}#body$/.test(id))).toHaveLength(4992);expect(ids).toContain('BESS#roof');expect(json.extensionsUsed).toContain('EXT_mesh_gpu_instancing');const {writeFile}=await import('node:fs/promises');await writeFile('artifacts/solarworld-assembled.glb',new Uint8Array(buffer));}
  finally{globalThis.FileReader=previous;}
 },15000);
});
