'use client';
import * as THREE from 'three';
import {source,qualification,parseConfig,type Config} from '../config/schema';
import {type Model,buildModel} from '../domain/model';
import {primitives} from '../geometry/primitives';
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();window.dispatchEvent(new CustomEvent('bess-export-ready',{detail:{url,name,size:blob.size}}));}
export function jsonExport(model:Model,camera?:Partial<Config['camera']>){const configuration=structuredClone(model.config);if(camera)Object.assign(configuration.camera,camera);return JSON.stringify({version:1,qualification,source,provenance:{source:'Supplied brief; temperature row interpretation provisional',assumptions:'Editable, unvalidated design choices; units mm unless otherwise stated',calculated:'Full-precision nominal DC results',terminals:'Illustrative; no supplier CAD',ratings:'Cable, fuse, fault, insulation and creepage ratings unspecified'},configuration,calculated:model.stats,topology:{equivalent:model.stats.equivalent,electrical:model.electrical,hydraulic:model.hydraulic},dimensions:model.dimensions,warnings:model.warnings},null,2);}
export function schedule(model:Model){const rows:[string,string,number,string,string][]=[];for(const node of model.nodes.filter(n=>n.kind!=='container'&&n.kind!=='ancillary'))rows.push([node.id,node.kind,1,node.parent??'',node.kind==='cell'?'LFP 314 Ah; supplied':node.kind==='pack'?'SB332314; supplied':'Custom; assumed']);for(const rack of model.racks){for(const type of ['Rack BMS','Fuse-disconnect','Contactor','Precharge circuit','Current sensor'])rows.push([`${rack.id}/${type.toUpperCase().replaceAll(' ','-')}`,type,1,rack.id,'Proposed; ratings unspecified']);}for(const pack of model.packs){rows.push([`${pack.id}/CMU`,'Cell monitor',1,pack.id,'Proposed; ratings unspecified']);rows.push([`${pack.id}/COLD-PLATE`,'Cold plate',1,pack.id,'Proposed; thermal capacity unspecified']);}for(const type of ['DC combiner','External PCS interface','Chiller','Pump','Reservoir','System BMS','Insulation monitoring'])rows.push([type.toUpperCase().replaceAll(' ','-'),type,1,'BESS','Proposed; ratings unspecified']);return rows;}
export function csvExport(model:Model){return '\uFEFF'+[['stable_id','component','quantity','parent','provenance'],...schedule(model)].map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\r\n');}
export async function glbExport(model:Model){const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');const c=structuredClone(model.config);c.explode=0;for(const k of Object.keys(c.visibility) as (keyof Config['visibility'])[])c.visibility[k]=true;const ps=primitives(buildModel(c),'BESS',true),group=new THREE.Group();group.name='Solarworld assembled BESS';group.userData={qualification,hiddenPartsIncluded:true,logicalPacks:model.stats.packs,logicalCells:model.stats.cells,units:'metres',axes:'X length / Y up / Z width',branding:'Text wordmark and DOM annotations are PNG-only; GLB contains geometry and node IDs.'};const batches=new Map<string,typeof ps>();for(const p of ps){const key=`${p.shape}-${p.color}-${p.metal}`;const batch=batches.get(key);if(batch)batch.push(p);else batches.set(key,[p]);}const geometries=[new THREE.BoxGeometry(1,1,1),new THREE.CylinderGeometry(1,1,1,8)],materials:InstanceType<typeof THREE.MeshStandardMaterial>[]=[];try{for(const parts of batches.values()){const p=parts[0],mat=new THREE.MeshStandardMaterial({color:p.color,metalness:p.metal?.5:.1,roughness:.6});materials.push(mat);const mesh=new THREE.InstancedMesh(geometries[p.shape==='box'?0:1],mat,parts.length),dummy=new THREE.Object3D();mesh.name=`${p.category}-${p.shape}`;mesh.userData.instanceIds=parts.map(x=>x.id);parts.forEach((p,i)=>{dummy.position.set(...p.position);dummy.scale.set(...p.size);dummy.quaternion.set(...(p.rotation??[0,0,0,1]));dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);});group.add(mesh);}group.updateMatrixWorld(true);const buffer=await new GLTFExporter().parseAsync(group,{binary:true,onlyVisible:false});if(!(buffer instanceof ArrayBuffer))throw new Error('Exporter did not return a binary model.');return new Blob([buffer],{type:'model/gltf-binary'});}finally{geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}}
export {parseConfig};
