import {roundRoute} from '../connectivity/routes';
import {type Model,type Vec,type Node,type Edge,add,m} from '../domain/model';
import type {Visibility} from '../config/schema';
export type Primitive={id:string;owner:string;shape:'box'|'cylinder';position:Vec;size:Vec;color:string;metal?:boolean;rotation?:[number,number,number,number];category:Visibility|'structure';};
export const palette={frame:'#253f4c',tray:'#b7c6cb',cell:'#407bab',cap:'#d0dde0',terminal:'#d8b876',lime:'#b4d858',supply:'#2d96d5',return:'#e7665c',hv:'#ee813c',bms:'#8c83b7',earth:'#8aa840'};
export function belongs(id:string,scope:string){return scope==='BESS'||id===scope||id.startsWith(scope+'/');}
export function displacement(node:Node|undefined,model:Model):Vec {if(!node)return [0,0,0];const e=model.config.explode;if(node.kind==='pack'||node.kind==='cell'){const pack=node.kind==='pack'?node:model.packs.find(p=>p.id===node.parent);const level=Number(pack?.id.split('/P')[1]??1)-1;return [0,e*(level*.23+(node.kind==='cell'?.32:0)),0];}return [0,0,0];}
export function primitives(model:Model,scope='BESS',assembled=false):Primitive[]{if(scope!=='BESS'&&model.nodes.find(n=>n.id===scope)?.kind==='ancillary')return primitives(model,'BESS',assembled).filter(p=>p.owner===scope);const out:Primitive[]=[],c=model.config,a=c.assumptions,d=model.dimensions,v=c.visibility,e=assembled?0:c.explode;const detail=scope!=='BESS';
 const box=(owner:string,tag:string,position:Vec,size:Vec,color:string,category:Primitive['category']='structure',metal=false)=>{out.push({id:`${owner}#${tag}`,owner,shape:'box',position,size,color,category,metal});};
 const cylinder=(owner:string,tag:string,from:Vec,to:Vec,r:number,color:string,category:Primitive['category'])=>{const dx=to[0]-from[0],dy=to[1]-from[1],dz=to[2]-from[2],len=Math.hypot(dx,dy,dz);if(len<1e-6)return;const dir=[dx/len,dy/len,dz/len];let q:[number,number,number,number]=[dir[2],0,-dir[0],1+dir[1]];const norm=Math.hypot(...q);q=norm<1e-8?[1,0,0,0]:q.map(x=>x/norm) as typeof q;out.push({id:`${owner}#${tag}`,owner,shape:'cylinder',position:[(from[0]+to[0])/2,(from[1]+to[1])/2,(from[2]+to[2])/2],size:[r,len,r],color,category,rotation:q});};
 if(scope==='BESS'){const [l,h,w]=d.enclosure;box('BESS','floor',[0,-.09,0],[l+.12,.18,w+.12],palette.frame);box('BESS','deck',[0,.015,0],[l,.025,w],'#d2dadd', 'structure',true);for(const x of [-l/2,l/2]){if(x<0){box('BESS','end-lower',[x,.23,0],[.07,.46,w],'#d8e2e6');box('BESS','end-upper',[x,(h+.64)/2,0],[.07,h-.64,w],'#d8e2e6');for(const sign of [-1,1])box('BESS',`gland-side${sign}`,[x,.55,sign*(w/4+.2)],[.07,.18,w/2-.4],'#d8e2e6');}else box('BESS',`end${x}`,[x,h/2,0],[.07,h,w],'#dbe4e7');for(const z of [-w/2,w/2])box('BESS',`corner${x}${z}`,[x,h/2,z],[.1,h,.1],palette.frame);}
 for(const z of [-w/2,w/2]){box('BESS',`rail${z}`,[0,h,z],[l,.09,.07],palette.frame);if(v.walls)box('BESS',`wall${z}`,[0,h/2,z],[l,h,.04],'#dae2e5','walls');}
 if(v.roof)box('BESS','roof',[0,h+.045+e*.6,0],[l+.1,.06,w+.1],'#eef1f2','roof',true);
 // Service zones are reserved geometry, not installed fire-safety hardware.
 box('BESS','reserved service zone',[l/2-m(a.endBay)/2,.04,0],[m(a.endBay)-.12,.012,w-.25],'#c8d8a8');
 for(const n of model.nodes.filter(n=>n.kind==='ancillary'&&!n.parent)){box(n.id,'body',n.position,n.size,n.id==='CHILLER'?'#dce6e8':palette.frame);box(n.id,'panel',add(n.position,[0,0,n.size[2]/2+.005]),[n.size[0]*.7,n.size[1]*.6,.014],n.id==='CHILLER'?palette.frame:'#8ba5ad');if(n.id==='CHILLER')for(let i=0;i<8;i++)box(n.id,`vent${i}`,add(n.position,[0,-.3+i*.08,.31]),[.46,.017,.025],'#5f7782');}}
 for(const rack of model.racks){if(!belongs(rack.id,scope)&&!belongs(scope,rack.id))continue;const [x,,z]=rack.position,[rx,rh,rz]=rack.size;if(scope==='BESS'||scope===rack.id){for(const dx of [-rx/2,rx/2])for(const dz of [-rz/2,rz/2])box(rack.id,`post${dx}${dz}`,[x+dx,rh/2,z+dz],[.034,rh,.034],palette.frame,'structure',true);for(const y of [.09,rh]){for(const dz of [-rz/2,rz/2])box(rack.id,`crossX${y}${dz}`,[x,y,z+dz],[rx,.035,.035],palette.frame);for(const dx of [-rx/2,rx/2])box(rack.id,`crossZ${y}${dx}`,[x+dx,y,z],[.035,.035,rz],palette.frame);}const sign=rack.bank===0?1:-1;box(rack.id,'controller',[x+.4,rh-.1,z+sign*rz/2],[.24,.14,.07],palette.frame,'bms');box(rack.id,'protection',[x,rh-.09,z+sign*rz/2],[.4,.12,.075],palette.frame);for(const [i,type] of ['Fuse-disconnect','Contactor','Precharge circuit','Current sensor'].entries())box(`${rack.id}/${type.toUpperCase().replaceAll(' ','-')}`,'proposed component',[x-.15+i*.1,rh-.09,z+sign*(rz/2+.045)],[.065,.075,.03],i===0?'#e4dcd0':i===2?palette.bms:'#728995');}}
 for(const pack of model.packs){if(!belongs(pack.id,scope)&&!belongs(scope,pack.id))continue;const pOffset:Vec=[0,e*(Number(pack.id.split('/P')[1])-1)*.23,0];const [x,y,z]=add(pack.position,pOffset),[px,py,pz]=pack.size,sign=pack.bank===0?1:-1;const cellScope=scope.includes('/C');if(!cellScope){box(pack.id,'tray',[x,y+m(a.wall)/2,z],[px,m(a.wall),pz],palette.tray,'structure',true);box(pack.id,'cold plate',[x,y+m(a.wall+a.coldPlate/2),z-sign*m(a.connector)/2],[px-.01,m(a.coldPlate),pz-m(a.connector)],'#80b7c7','structure',true);for(const dx of [-px/2,px/2])box(pack.id,`side${dx}`,[x+dx,y+py/2,z],[m(a.wall),py,pz],palette.tray,'structure',true);for(const dz of [-pz/2+m(a.compression)/2,pz/2-m(a.connector+a.compression/2)])box(pack.id,`compression${dz}`,[x,y+py/2,z+sign*dz],[px,m(a.cellHeight),m(a.compression)],palette.tray,'structure',true);
 box(pack.id,'front',[x,y+py/2,z+sign*pz/2],[px,py,.014],'#cbd6dc','structure',true);box(pack.id,'nameplate',[x,y+py*.52,z+sign*(pz/2+.009)],[.2,.095,.009],palette.frame);box(pack.id,'insulation',[x,y+m(a.wall+a.coldPlate)+.002,z-sign*m(a.connector)/2],[px-.015,.003,pz-m(a.connector)-2*m(a.compression)],'#e5e8dd');if(v.lids)box(pack.id,'lid',[x,y+py+.008+e*.45,z],[px,.009,pz],palette.tray,'lids',true);
 if(v.bms)box(pack.id,'cell monitor',[x+.52,y+py-.04,z+sign*(pz/2+.015)],[.17,.075,.025],'#557b53','bms');
 for(const [key,color] of [['supply',palette.supply],['return',palette.return]] as const){const port=model.hydraulic.ports[`${pack.id}:${key}`];if(v.coolant)cylinder(pack.id,key,add(port.position,pOffset),add(add(port.position,pOffset),[0,0,.04*sign]),.017,color,'coolant');}
 for(const pol of ['+','-']){const port=model.electrical.ports[`${pack.id}:${pol}`];box(pack.id,`terminal${pol}`,add(port.position,pOffset),[.038,.025,.022],palette.hv,'structure');}
 }
 }
 if(v.cells)for(const cell of model.cells){if(!belongs(cell.id,scope))continue;const pos=assembled?cell.position:add(cell.position,displacement(cell,model));box(cell.id,'body',pos,cell.size,palette.cell,'cells',true);if(detail||Number(cell.parent?.split('/P')[1])===model.stats.seriesPacks){box(cell.id,'cap',add(pos,[0,cell.size[1]/2-.003,0]),[cell.size[0],.006,cell.size[2]],palette.cap,'cells',true);box(cell.id,'vent',add(pos,[0,cell.size[1]/2+.002,0]),[.037,.003,.016],palette.frame,'cells');for(const pol of ['+','-']){const pt=model.electrical.ports[`${cell.id}:${pol}`].position;box(cell.id,pol,assembled?pt:add(pt,displacement(cell,model)),[.024,.009,.016],palette.terminal,'cells',true);}}}
 const route=(edge:Edge)=>{if(e>0)return;const graph=edge.kind.startsWith('coolant')||edge.kind==='coldPlate'?model.hydraulic:model.electrical;const f=graph.ports[edge.from],t=graph.ports[edge.to];if(!belongs(f.node,scope)||!belongs(t.node,scope))return;const kind=edge.kind;const category:Primitive['category']=kind==='busbar'?'busbars':kind==='hv'?'hv':kind==='bms'?'bms':kind==='earth'?'earth':'coolant';if(!v[category as Visibility]||kind==='coldPlate')return;const color=kind==='busbar'?'#c49b5b':kind==='hv'?palette.hv:kind==='earth'?palette.earth:kind==='bms'?palette.bms:kind==='coolantSupply'?palette.supply:palette.return;const routed=kind==='busbar'?edge.points:roundRoute(edge.points,m(a.bendRadius));for(let i=1;i<routed.length;i++)cylinder(f.node,`${edge.id}/${i}`,routed[i-1],routed[i],kind==='busbar'?.0035:kind==='bms'?.004:kind==='hv'?.011:.009,c.highlight&&belongs(f.node,scope==="BESS"?'R01':scope)?'#c6ed5a':color,category);};
 model.electrical.edges.forEach(route);model.hydraulic.edges.forEach(route);return out.filter(p=>p.category!=='bms'||v.bms);
}
