import { z } from 'zod';
export const source = Object.freeze({packModel:'SB332314',chemistry:'LFP',cellVoltage:3.2,cellAh:314,cellThickness:71.7,cellWidth:174,cellWidthRange:[173.5,174],cellHeight:207,cellHeightRange:[206.8,207.2],seriesCells:104,parallelCells:1,rows:8,columns:13,packVoltage:332.8,packAh:314,packEnergyLabel:104.45,current:157,packMaxVoltage:379.6,packMinVoltage:260,chargeTemperature:[0,55],dischargeTemperature:[-10,55],targetEnergyLabel:5015,targetHours:2});
const mm=(min:number,max:number)=>z.number().finite().min(min).max(max);
export const assumptionsSchema=z.object({cellWidth:mm(173.5,174),cellHeight:mm(206.8,207.2),cellGap:mm(0,20),rowGap:mm(0,30),compression:mm(5,80),wall:mm(1,20),coldPlate:mm(3,40),terminalClearance:mm(12,100),connector:mm(30,180),rackGap:mm(60,500),verticalGap:mm(50,300),aisle:mm(600,1800),requiredAisle:mm(600,1800),endBay:mm(450,2200),bendRadius:mm(10,80),manual:z.boolean(),length:mm(1000,25000),width:mm(1000,8000),height:mm(500,5000)}).strict();
export const visibilitySchema=z.object({roof:z.boolean(),walls:z.boolean(),lids:z.boolean(),cells:z.boolean(),busbars:z.boolean(),hv:z.boolean(),earth:z.boolean(),coolant:z.boolean(),bms:z.boolean(),labels:z.boolean(),dimensions:z.boolean()}).strict();
export const cameraSchema=z.object({view:z.enum(['iso','top','front','side']),position:z.tuple([z.number().finite(),z.number().finite(),z.number().finite()]).nullable(),target:z.tuple([z.number().finite(),z.number().finite(),z.number().finite()]).nullable(),zoom:z.number().finite().min(.01).max(100000)}).strict();
export const configSchema=z.object({version:z.literal(1),preset:z.enum(['reference','alternative']),assumptions:assumptionsSchema,equipment:z.object({maxVoltage:z.number().positive().max(10000).nullable(),minVoltage:z.number().nonnegative().max(10000).nullable(),maxCurrent:z.number().positive().max(100000).nullable()}).strict(),usable:z.object({soc:z.number().positive().max(1).nullable(),efficiency:z.number().positive().max(1).nullable(),auxKW:z.number().nonnegative().max(100000).nullable(),acKW:z.number().positive().max(100000).nullable(),constantDCKW:z.number().positive().max(100000).nullable()}).strict(),visibility:visibilitySchema,camera:cameraSchema,explode:z.number().min(0).max(1),presentation:z.boolean(),highlight:z.boolean(),logo:z.string().max(2000000).regex(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/).nullable()}).strict();
export type Config=z.infer<typeof configSchema>;
export type Visibility=keyof Config['visibility'];
export const defaults:Config={version:1,preset:'reference',assumptions:{cellWidth:174,cellHeight:207,cellGap:1.5,rowGap:3,compression:12,wall:3,coldPlate:12,terminalClearance:28,connector:70,rackGap:120,verticalGap:125,aisle:850,requiredAisle:800,endBay:1050,bendRadius:25,manual:false,length:12000,width:3500,height:2600},equipment:{maxVoltage:1500,minVoltage:null,maxCurrent:null},usable:{soc:null,efficiency:null,auxKW:null,acKW:null,constantDCKW:null},visibility:{roof:false,walls:false,lids:false,cells:true,busbars:false,hv:true,earth:false,coolant:true,bms:false,labels:true,dimensions:false},camera:{view:'iso',position:null,target:null,zoom:1},explode:0,presentation:false,highlight:false,logo:null};
export const qualification='Concept engineering visualization. Equipment ratings, detailed mechanical design and usable AC performance require validation.';
export function parseConfig(text:string):Config {const data=JSON.parse(text); if(!data || (data.version!==undefined&&data.version!==1) || canonical(data.source)!==canonical(source))throw new Error('Source inputs do not match the version 1 supplied specification.');return configSchema.parse(data.configuration);}

function canonical(value:unknown):string{if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical((value as Record<string,unknown>)[k])).join(',')+'}';return JSON.stringify(value);}
