'use client';
import {create} from 'zustand';
import {configSchema,defaults,parseConfig,source,type Config} from '../config/schema';
import type {SiteSpec} from '../geometry/site';
/** Where a studio configuration is kept between visits. The old vendor-named key is read once so
 *  a configuration saved before the platform was white-labelled is not lost. */
export const STUDIO_KEY='bess-studio-v1';
let initial=structuredClone(defaults),initialError='';try{const saved=localStorage.getItem(STUDIO_KEY)??localStorage.getItem('solarworld-bess-v1');if(saved)initial=parseConfig(saved);}catch{initialError='Saved configuration could not be read. Baseline restored.';}
export const useStudio=create<{config:Config;selected:string;scope:string;revision:number;message:string;brandName:string;site:SiteSpec|null;update:(f:(c:Config)=>void)=>void;select:(id:string)=>void;focus:(id:string)=>void;reset:()=>void;import:(c:Config)=>void;notify:(s:string)=>void;setBrand:(name:string)=>void;setSite:(s:SiteSpec|null)=>void}>(set=>({config:initial,selected:'BESS',scope:'BESS',revision:0,message:initialError,brandName:'',setBrand:brandName=>set(s=>s.brandName===brandName?s:{brandName}),site:null,setSite:site=>set(s=>JSON.stringify(s.site)===JSON.stringify(site)?s:{site,...(site?{}:s.scope==='SITE'?{scope:'BESS',selected:'BESS',revision:s.revision+1}:{})}),update:f=>set(s=>{const c=structuredClone(s.config);f(c);const result=configSchema.safeParse(c);if(!result.success)return {message:result.error.issues[0].message};let message='';try{localStorage.setItem(STUDIO_KEY,JSON.stringify({source,configuration:c}));}catch{message='Local storage is full or unavailable. Export JSON to keep this configuration.';}return {config:c,message};}),select:selected=>set({selected}),focus:scope=>set(s=>({scope,selected:scope,revision:s.revision+1})),reset:()=>{localStorage.removeItem(STUDIO_KEY);localStorage.removeItem('solarworld-bess-v1');set(s=>({config:structuredClone(defaults),scope:'BESS',selected:'BESS',revision:s.revision+1,message:'Baseline restored.'}));},import:config=>{localStorage.setItem(STUDIO_KEY,JSON.stringify({source,configuration:config}));set(s=>({config,scope:'BESS',selected:'BESS',revision:s.revision+1,message:'Configuration imported.'}));},notify:message=>set({message})}));

/** Filename stem for exports, so a download carries the organization rather than a fixed vendor. */
export const brandSlug = (name: string) => (name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'bess') + '-bess';
