import { describe, it } from 'vitest';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { defaultSizingInput, sizeSystem, recoveryHours, enclosureHierarchy } from '../src/sizing/engine';
import { evaluateFinance } from '../src/sizing/finance';
import { defaultPriceBook } from '../src/catalog/pricing';
import * as units from '../src/domain/units';
import type { ApplicationId } from '../src/sizing/applications';

/**
 * Ten sizes, every line of the derivation, written out for a person to check.
 *
 * `npm run audit`. Not a test — a printer. Assertions catch a rule being broken; this catches a
 * rule that was never right, by putting the whole chain from two typed numbers to a quantity of
 * equipment on one page where the arithmetic can be followed by hand. Four separate faults came out
 * of the first run of it: a granularity figure measured on the wrong chain, auxiliary consumption
 * on the air-cooled racks that was a hundred times what a management board draws, converter
 * rounding that appeared nowhere, and an auxiliary allowance that turned 1.87 enclosures into 3
 * with nothing on the page to say so.
 */
const fx = defaultPriceBook.landed.exchangeRateInrPerUsd;
const inr = (usd: number) => { const v = usd * fx; return v >= 1e7 ? `₹${(v / 1e7).toFixed(2)} cr` : v >= 1e5 ? `₹${(v / 1e5).toFixed(2)} L` : `₹${Math.round(v).toLocaleString('en-IN')}`; };
const rate = (usd: number, kwh: number) => `₹${Math.round(usd * fx / kwh).toLocaleString('en-IN')}`;

const DUTIES: [number, number, ApplicationId][] = [
  [0.005, 1, 'backup-power'], [0.05, 2, 'peak-shaving'], [0.1, 4, 'backup-power'],
  [0.5, 2, 'peak-shaving'], [1, 1, 'frequency-regulation'], [2, 4, 'solar-shifting'],
  [5, 1, 'energy-arbitrage'], [5, 4, 'energy-arbitrage'], [20, 2, 'peak-shaving'],
  [50, 4, 'energy-arbitrage'],
];

describe('sizing audit', () => {
  it('writes the derivation for ten sizes', () => {
    const out: string[] = [];
    const w = (s = '') => out.push(s);
    w('# Ten sizes, line by line');
    w('');
    w('Generated by `npm run audit`. Every step from the two numbers a person types to the quantity '
      + 'of equipment on the invoice, so the arithmetic can be followed by hand rather than trusted.');
    w('');
    w('| Asked | Contracted | Nominal installed | Deliverable day one | Equipment | Conversion | Supply | Installed |');
    w('| --- | ---: | ---: | ---: | --- | --- | ---: | ---: |');
    const sized = DUTIES.map(([mw, h, app]) => {
      const b = defaultSizingInput(app);
      const s = sizeSystem({ ...b, mode: 'power-duration', powerMW: mw, durationH: h, chargeDurationH: recoveryHours(h, b.losses) });
      return { s, f: evaluateFinance(s, defaultPriceBook), mw, h, app };
    });
    for (const { s, f, mw, h } of sized) {
      w(`| ${units.powerText(mw)} × ${h} h | ${units.energyText(s.requiredUsableMWh)} | `
        + `${units.energyText(s.installedDcMWh)} | ${units.energyText(s.day1UsableMWh)} | `
        + `${s.units} × ${s.enclosure.model} | ${s.pcsCount} × ${s.pcs.ratedKW} kW | `
        + `${inr(f.capexUsd)} | ${inr(f.indicativeInstalledUsd ?? f.capexUsd)} |`);
    }
    w('');
    for (const { s, f, mw, h, app } of sized) {
      const r = s.rationale;
      w(`## ${units.powerText(mw)} for ${h} h · ${app}`);
      w('');
      w(`Contracted **${units.energyText(s.requiredUsableMWh)}** at **${units.powerText(s.ratedPowerMW)}**, `
        + `recharged over ${s.input.chargeDurationH} h (${s.recoveryDurationH.toFixed(2)} h at rated power).`);
      w('');
      for (const [title, chain, needs] of [['Energy', r.energy, r.unitsForEnergy], ['Power', r.power, r.unitsForPower]] as const) {
        w(`**${title} — needs ${needs}**`);
        w('');
        w('| Step | Figure | Why |');
        w('| --- | ---: | --- |');
        for (const st of chain) {
          const v = st.unit === 'units' ? `${st.value.toFixed(0)}` : st.unit === 'MW' ? units.powerText(st.value) : units.energyText(st.value);
          w(`| ${st.label} | **${v}** | ${st.detail} |`);
        }
        w('');
      }
      w(`**${r.units} × ${enclosureHierarchy(s.enclosure)}**`);
      w('');
      w(`${units.energyText(r.installedDcMWh)} of nameplate, ${units.energyText(s.day1UsableMWh)} deliverable on day one `
        + `(${(100 * s.day1UsableMWh / s.installedDcMWh).toFixed(0)}% of nameplate, `
        + `${(s.day1UsableMWh / s.requiredUsableMWh).toFixed(2)}× the contracted energy). `
        + `${s.pcsCount} × ${s.pcs.ratedKW} kW of conversion against ${units.powerText(s.ratedPowerMW)} contracted`
        + `${s.transformer ? `, ${s.transformerCount} × ${s.transformer.ratedKVA} kVA of transformation` : ', no transformer'}. `
        + `Discharge ${s.systemCRate.toFixed(2)} C and charge ${s.chargeCRate.toFixed(2)} C against ${s.packCRate.toFixed(2)} C the pack sustains. `
        + `${(s.rteAc * 100).toFixed(1)}% round trip at the connection. `
        + `${s.augmentations.length} augmentation${s.augmentations.length === 1 ? '' : 's'} over ${s.input.projectYears} years.`);
      w('');
      w(`${inr(f.capexUsd)} delivered — ${rate(f.capexUsd, s.installedDcMWh * 1000)} per kWh of nameplate, `
        + `${rate(f.capexUsd, s.requiredUsableMWh * 1000)} per kWh contracted. `
        + `${inr(f.indicativeInstalledUsd ?? f.capexUsd)} installed, indicative.`);
      w('');
      if (r.reasons.length) {
        w('**Why it is larger than the duty**');
        w('');
        for (const x of r.reasons) w(`- ${x.text}`);
        w('');
      }
      const raised = s.warnings.filter(x => x.level !== 'info');
      if (raised.length) {
        w('**Raised**');
        w('');
        for (const x of raised) w(`- *${x.level}* — ${x.text}`);
        w('');
      }
    }
    w('---');
    w('');
    w('*Developed and managed by jouleWise Technologies · www.joulewise.com*');
    writeFileSync(join(import.meta.dirname, '..', 'docs', 'SIZING-AUDIT.md'), out.join('\n') + '\n');
    process.stdout.write('\nwrote docs/SIZING-AUDIT.md\n');
  });
});
