"""Join what the studio says to what SAM says, and report where they part company.

Writes `docs/VALIDATION.md`, which is committed, so the divergence is in the repository for
somebody who has not installed a 47 MB Python dependency. Exits non-zero if a check that is
expected to agree does not, so this can be run in anger rather than only read.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent

# How far apart the two may be before it is a finding rather than a rounding difference. Declared
# here, ahead of the numbers, because a tolerance written after the measurement is a description.
TOLERANCE = {
    'deliverable': 0.06,   # 6%: the studio strikes nameplate at nominal voltage, SAM integrates the curve
    'roundTrip': 0.04,     # 4%: the supplied sheet's DC figure against SAM's resistance band
}


def pct(x: float) -> str:
    return f'{x * 100:.1f}%'


def signed(x: float) -> str:
    return f'{x * 100:+.1f}%'


def main() -> int:
    cases = json.loads((HERE / 'cases.json').read_text())
    sam = json.loads((HERE / 'sam.json').read_text())
    by_id = {r['id']: r for r in sam['results']}
    years = cases['years']
    failures: list[str] = []
    lines: list[str] = []

    w = lines.append
    w('# Validating the sizing engine against NREL SAM')
    w('')
    w('Generated by `npm run validate`. The studio\'s own cases are put through '
      f'**{sam["engine"]} {sam["version"]}** and the two answers are set beside each other.')
    w('')
    w('The point is not that SAM is right and the studio is wrong. It is that two implementations '
      'written from different starting points should agree about the same physics, and wherever '
      'they do not, the disagreement names an assumption somebody has to own.')
    w('')
    w('## What is compared, and what is not')
    w('')
    w('| Quantity | Studio | SAM | Comparable |')
    w('| --- | --- | --- | --- |')
    w('| Deliverable DC energy across the usable window | nameplate × window × depth of discharge, '
      'nameplate struck at the cell\'s nominal voltage | integrates the Shepherd discharge curve '
      'from the top of the window to the bottom at the design rate | **yes** |')
    w('| DC round-trip efficiency | a flat figure from the supplied sizing sheet | ohmic and '
      'polarisation losses through a discharge and the recharge that follows | **yes** |')
    w('| Capacity retention over the project life | a supplied 20-year schedule, or a cycle-and-'
      'calendar model with an Arrhenius temperature term | three separate lifetime models, which '
      'disagree with each other | **yes, with care** |')
    w('| Terminal voltage under load | the pack\'s stated window, from cell limits × string depth | '
      'the voltage actually reached at the design current | **yes** |')
    w('| Equipment selection, landed cost, augmentation scheduling, quotations | the studio | — | '
      'no: SAM does not model them |')
    w('| Weather, irradiance, market dispatch | — | SAM | no: the studio takes a duty as given |')
    w('')
    w('## Assumptions this comparison had to supply')
    w('')
    w('SAM needs two things the studio\'s catalogue does not carry. They are named here rather than '
      'buried in the harness, because a cross-check whose own inputs are invented is not a check.')
    w('')
    a = sam['assumptions']
    w(f'- **Cell DC resistance.** The published AC impedance for the 314 Ah prismatic in this '
      f'catalogue is ≤ 0.18 mΩ, and DC resistance for LFP prismatics runs roughly one and a half to '
      f'two times that. Every efficiency check is therefore run at both '
      f'{a["resistanceMilliOhmPerCell"]["optimistic"]} mΩ and '
      f'{a["resistanceMilliOhmPerCell"]["realistic"]} mΩ per cell and reported as a band.')
    c = a['lfpCurve']
    w(f'- **The discharge curve.** The catalogue gives a cell\'s nominal, maximum and minimum '
      f'voltage and no shape between them, and SAM\'s own `LFPGraphite` preset carries NREL\'s '
      f'lifetime configuration beside a voltage curve that is NMC-shaped — 4.1 V full, 3.4 V '
      f'nominal. Left at that it put the whole discharge at 3.57 V per cell and claimed a container '
      f'delivers its entire nameplate across a 90% window. The Shepherd knees are placed where a '
      f'published LFP cell has them: {c["vexp"]} V at {c["qexp_fraction"]:.0%} discharged, '
      f'{c["vnom"]} V at {c["qnom_fraction"]:.0%}.')
    w('')

    # ------------------------------------------------------------ deliverable --
    w('## 1 · Deliverable DC energy across the usable window')
    w('')
    w('One enclosure, discharged at the design rate from the top of its state-of-charge window to '
      'the bottom.')
    w('')
    w('| Case | Enclosure | Studio | SAM | Divergence | Mean V/cell |')
    w('| --- | --- | ---: | ---: | ---: | ---: |')
    for case in cases['cases']:
        r = by_id[case['id']]['deliverable']['realistic']
        studio = case['studio']['storedDcKWh']
        d = (r['kwh'] - studio) / studio
        flag = '' if abs(d) <= TOLERANCE['deliverable'] else ' ⚠'
        if abs(d) > TOLERANCE['deliverable']:
            failures.append(f'deliverable energy, {case["label"]}: {signed(d)}')
        w(f'| {case["label"]} | {case["plant"]["enclosureModel"]} | {studio:,.1f} kWh | '
          f'{r["kwh"]:,.1f} kWh | {signed(d)}{flag} | {r["meanVPerCell"]:.3f} |')
    w('')
    w('The studio strikes nameplate energy at the cell\'s nominal voltage and SAM integrates the '
      'real curve, whose mean sits a little above nominal across an LFP plateau. The studio is '
      'therefore expected to read slightly low, and a **conservative** usable-energy figure is the '
      'right direction for a number a contract is written against.')
    w('')

    # -------------------------------------------------------------- round trip --
    w('## 2 · DC round-trip efficiency')
    w('')
    w('**SAM is not the authority here, and the check is not symmetric.** `BatteryStateful` models '
      'the ohmic and polarisation loss of the Thevenin circuit and nothing else: no coulombic '
      'inefficiency, no hysteresis between the charge and discharge curves, no self-discharge. Its '
      'answer is therefore a *floor on the loss* — the least the physics can cost — and a real LFP '
      'system measured at its DC terminals lands several points below it. What this establishes is '
      'that the studio\'s flat figure is on the conservative side of the floor, and by how much.')
    w('')
    w('| Case | Design C-rate | Studio | SAM ohmic floor, 0.18 mΩ | at 0.36 mΩ | Conservative |')
    w('| --- | ---: | ---: | ---: | ---: | :---: |')
    for case in cases['cases']:
        rt = by_id[case['id']]['roundTrip']
        studio = case['studio']['dcRoundTrip']
        lo, hi = rt['realistic']['dcRoundTrip'], rt['optimistic']['dcRoundTrip']
        # The meaningful direction: the studio must not claim less loss than the physics demands.
        conservative = studio <= min(lo, hi) + 1e-9
        if not conservative:
            failures.append(f'DC round trip, {case["label"]}: studio claims {pct(studio)}, above '
                            f'the ohmic floor of {pct(min(lo, hi))} — less loss than the circuit allows')
        w(f'| {case["label"]} | {case["conditions"]["systemCRate"]:.2f} C | {pct(studio)} | '
          f'{pct(hi)} | {pct(lo)} | {"yes" if conservative else "**no**"} |')
    w('')
    w('The studio\'s figure is a **constant**, and the ohmic floor is not: loss rises with the '
      'square of the current, so the margin between them closes as the C-rate rises. Across the '
      'rates the studio actually designs at — 0.14 C to 0.49 C — the constant is comfortably '
      'conservative. It would stop being so somewhere above 1 C, which is outside anything in this '
      'catalogue but inside what a frequency-regulation product could ask for. Worth revisiting if '
      'a high-rate cell enters the catalogue.')
    w('')

    # --------------------------------------------------------------- retention --
    w('## 3 · Capacity retention over the project life')
    w('')
    w('This is where the models disagree, and where they disagree with each other more than with '
      'the studio. SAM ships three lifetime models; all three were run at the same duty, depth and '
      'cell temperature as the studio\'s own design.')
    w('')
    for case in cases['cases']:
        r = by_id[case['id']]['retention']
        cond, duty = case['conditions'], case['duty']
        w(f'### {case["label"]}')
        w('')
        w(f'{cond["efcPerYear"]:.0f} equivalent full cycles a year at {cond["cellTempC"]:.1f} °C, '
          f'{duty["cyclesPerDay"]} cycles a day over {duty["projectYears"]} years.')
        w('')
        w('| Year | Studio, supplied schedule | Studio, ageing model | ' +
          ' | '.join(r.keys()) + ' |')
        w('| --- |' + ' ---: |' * (2 + len(r)))
        for y in years:
            row = [f'| {y} ', f'| {pct(case["studio"]["retentionSupplied"][str(y)])} ',
                   f'| {pct(case["studio"]["retentionModel"][str(y)])} ']
            for name in r:
                v = r[name].get(str(y))
                row.append(f'| {pct(v) if v is not None else "—"} ')
            w(''.join(row) + '|')
        w('')
    w('**Read this as a spread, not a verdict.** Where SAM\'s own three models differ by twenty '
      'points at year twenty, no single one of them settles what a plant will do; what the check '
      'establishes is whether the studio\'s schedule sits inside the range of published models '
      'rather than outside it, and how much of the augmentation programme — and therefore the '
      'price — rests on a number nobody can pin down. It is the strongest argument in the product '
      'for a supplier warranty curve replacing the default.')
    w('')

    # ----------------------------------------------------------------- voltage --
    w('## 4 · Terminal voltage under load')
    w('')
    w('The studio takes the string window from the cell limits times the string depth, and warns '
      'when it falls outside the converter\'s DC input. SAM reports the voltage actually reached at '
      'the design current, which is what the converter sees.')
    w('')
    w('| Case | Studio window, V/cell | SAM under load, V/cell | Converter |')
    w('| --- | ---: | ---: | --- |')
    for case in cases['cases']:
        d = by_id[case['id']]['deliverable']['realistic']
        rt = by_id[case['id']]['roundTrip']['realistic']
        cell = case['plant']['cell']
        n = case['plant']['cellsInSeries']
        w(f'| {case["label"]} | {cell["minV"]:.2f} – {cell["maxV"]:.2f} | '
          f'{d["minVPerCell"]:.3f} – {max(d["maxVPerCell"], rt["chargeMaxV"] / n):.3f} | '
          f'{case["plant"]["pcsModel"]} |')
    w('')
    w('The studio\'s window is the protection envelope — the voltages the cell may legally reach — '
      'and SAM\'s is the working range at this duty. The first is correctly the wider of the two: '
      'a converter has to be specified for the envelope, not for the average day.')
    w('')

    # ------------------------------------------------------------------ result --
    w('## Result')
    w('')
    if failures:
        w(f'**{len(failures)} check(s) outside tolerance:**')
        w('')
        for f in failures:
            w(f'- {f}')
    else:
        w('Every check that is expected to agree agrees, inside the tolerances declared above. The '
          'retention spread is reported rather than asserted, because the published models do not '
          'agree with each other.')
    w('')
    w('---')
    w('')
    w('*Developed and managed by jouleWise Technologies · www.joulewise.com*')

    (ROOT / 'docs' / 'VALIDATION.md').write_text('\n'.join(lines) + '\n')
    print('wrote docs/VALIDATION.md')
    for f in failures:
        print(f'  OUTSIDE TOLERANCE: {f}')
    return 1 if failures else 0


if __name__ == '__main__':
    sys.exit(main())
