import { describe, it } from 'vitest';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { defaultSizingInput, sizeSystem, recoveryHours, enclosureHierarchy, type SizingInput, type SizingResult } from '../src/sizing/engine';
import { evaluateFinance, landedForSizing, type FinanceResult } from '../src/sizing/finance';
import { defaultPriceBook, formatMoney, landedRatesFor } from '../src/catalog/pricing';
import { buildQuoteLines, uplift } from '../src/quoting/quote';
import * as u from '../src/domain/units';
import { packOf, cellOf } from '../src/catalog/products';

/**
 * A worked quotation for one duty, with every figure traced to where it came from.
 *
 * `npm run quote`. Not a substitute for raising one in the studio — the same functions produce
 * both — but a form that can be read, checked and argued with outside the application.
 */
const pb = { ...defaultPriceBook, currency: 'INR' as const };
const fx = pb.landed.exchangeRateInrPerUsd;
const inr = (usd: number) => formatMoney(usd * fx, 'INR', true);
const exact = (usd: number) => `₹${Math.round(usd * fx).toLocaleString('en-IN')}`;
const pc = (x: number) => `${(x * 100).toFixed(1)}%`;

const design = (label: string, over: Partial<SizingInput>) => {
  const base = defaultSizingInput('peak-shaving');
  const sizing = sizeSystem({
    ...base, mode: 'power-duration', powerMW: 1, durationH: 5,
    chargeDurationH: recoveryHours(5, base.losses), transformerId: 'tx-1600', gridKV: 11, ...over,
  });
  return { label, sizing, finance: evaluateFinance(sizing, pb) };
};

const costTable = (w: (s?: string) => void, sizing: SizingResult, finance: FinanceResult) => {
  const lines = buildQuoteLines(sizing, finance, 'INR', pb).filter(l => !l.optional);
  const factor = uplift(finance);
  w('| # | Item | Quantity | Rate | Amount | Basis |');
  w('| --- | --- | ---: | ---: | ---: | --- |');
  lines.forEach((l, i) => w(`| ${i + 1} | ${l.label} | ${l.quantity.toLocaleString('en-IN')} ${l.unit} `
    + `| ₹${Math.round(l.unitPrice).toLocaleString('en-IN')} | ₹${Math.round(l.total).toLocaleString('en-IN')} `
    + `| ${l.note ?? '—'} |`));
  const subtotal = lines.reduce((s, l) => s + l.total, 0);
  w(`| | **Order value** | | | **₹${Math.round(subtotal).toLocaleString('en-IN')}** | `
    + `Rates carry ${pc(factor - 1)} of contingency and margin inside them |`);
  w('');
};

describe('worked quotation', () => {
  it('writes a 1 MW / 5 MWh costing', () => {
    const out: string[] = [];
    const w = (s = '') => out.push(s);

    const contracted = design('Reading A — 5 MWh delivered to the load', {});
    // No augmentation: the plant a buyer of one container actually gets, with no further capital
    // after day one. Contracted at what it still delivers in its twentieth year, because a figure
    // it only meets while new is not a figure to write into a contract — and because a single
    // container sized to its year-one yield needs a *second whole container* the moment it fades,
    // which doubles the plant to hold a duty it was never quite able to carry.
    const oneContainer = (durationH: number) => design('x', {
      equipment: 'pinned', enclosureId: 'enc-5mwh-20ft', pcsId: 'pcs-1725', durationH,
      augmentation: 'none', chargeDurationH: recoveryHours(durationH, defaultSizingInput('peak-shaving').losses),
    }).sizing;
    const holds = (h: number) => { const s = oneContainer(h); return s.units === 1 && !s.years.some(y => y.shortfall); };
    let lo = 0.5, hi = 5;
    for (let i = 0; i < 40; i++) { const mid = (lo + hi) / 2; if (holds(mid)) lo = mid; else hi = mid; }
    const hours = Math.floor(lo * 100) / 100;
    const nameplate = design('Reading B — one 5 MWh container, held for twenty years', {
      equipment: 'pinned', enclosureId: 'enc-5mwh-20ft', pcsId: 'pcs-1725', durationH: hours,
      augmentation: 'none', chargeDurationH: recoveryHours(hours, defaultSizingInput('peak-shaving').losses),
    });

    w('# 1 MW / 5 MWh container BESS — costing');
    w('');
    w('Generated by `npm run quote` from the same sizing and pricing the studio raises a quotation '
      + 'with. Default price book, landed-import basis, supply-only scope, rupees at '
      + `₹${fx}/US$.`);
    w('');
    w('## The question "1 MW / 5 MWh" does not settle');
    w('');
    w('Five megawatt-hours **delivered to the load** and five megawatt-hours **of nameplate** are '
      + 'different plants, and the gap is about a factor of two. Both are priced below, and which '
      + 'one is meant is the first thing to settle before anybody quotes.');
    w('');
    w('| Reading | Contracted at the load | Nameplate installed | Duration at 1 MW | Containers | Conversion | Order value |');
    w('| --- | ---: | ---: | ---: | --- | --- | ---: |');
    for (const d of [contracted, nameplate]) {
      w(`| ${d.label.split('—')[1].trim()} | ${u.energyText(d.sizing.requiredUsableMWh)} | `
        + `${u.energyText(d.sizing.installedDcMWh)} | ${d.sizing.effectiveDurationH.toFixed(2)} h | `
        + `${d.sizing.units} × ${d.sizing.enclosure.model} | `
        + `${d.sizing.pcsCount} × ${d.sizing.pcs.ratedKW} kW | ${inr(d.finance.capexUsd)} |`);
    }
    w('');
    w('A 5 MWh container is 5 MWh of **nameplate**. Between that and the meter sit the usable '
      + 'state-of-charge window, the depth of discharge, the conversion path, the auxiliaries and '
      + 'the capacity the cells will have lost by the end of the year the plant is sized for. One '
      + `container carries 1 MW for **${nameplate.sizing.effectiveDurationH.toFixed(2)} h** across twenty `
      + 'years with nothing added, not five. Five hours at the load takes two of them.');
    w('');
    w('What one container gives at 1 MW, as the cells age:');
    w('');
    w('| | At commissioning | End of year 1 | End of year 10 | End of year 20 |');
    w('| --- | ---: | ---: | ---: | ---: |');
    const one = nameplate.sizing;
    const at = (y: number) => one.years[y]?.usableMWh ?? 0;
    w(`| Deliverable | ${u.energyText(one.day1UsableMWh)} | ${u.energyText(at(1))} | ${u.energyText(at(10))} | ${u.energyText(at(20))} |`);
    w(`| Hours at 1 MW | ${one.day1UsableMWh.toFixed(2)} h | ${at(1).toFixed(2)} h | ${at(10).toFixed(2)} h | ${at(20).toFixed(2)} h |`);
    w('');
    w('A contract is written against the last of those, not the first. Sizing a single container to '
      + 'its year-one figure leaves it needing a **second whole container** the moment it fades — '
      + 'doubling the plant to hold a duty it was never quite able to carry.');
    w('');

    for (const { label, sizing, finance } of [contracted, nameplate]) {
      const r = sizing.rationale;
      const enc = sizing.enclosure, pack = packOf(enc), cell = cellOf(pack);
      const landed = landedForSizing(sizing, pb);
      const rates = landedRatesFor(pb, enc.id);
      w(`## ${label}`);
      w('');
      w('### The plant');
      w('');
      w(`- **${sizing.units} × ${enclosureHierarchy(enc)}**`);
      w(`- ${sizing.pcsCount} × ${sizing.pcs.model} — ${u.powerText(sizing.pcsCount * sizing.pcs.ratedKW / 1000)} of conversion against ${u.powerText(sizing.ratedPowerMW)} contracted`);
      w(`- ${sizing.transformer ? `${sizing.transformerCount} × ${sizing.transformer.model}, ${sizing.transformer.lvKV}/${sizing.transformer.hvKV} kV` : 'No transformer — connection at the converter terminals'}`);
      w(`- ${sizing.cells.toLocaleString('en-IN')} × ${cell.model} in ${sizing.packs.toLocaleString('en-IN')} packs, ${sizing.strings} parallel strings, ${sizing.dcVoltageWindow[0]}–${sizing.dcVoltageWindow[1]} V DC`);
      w(`- ${u.energyText(sizing.installedDcMWh)} nameplate · ${u.energyText(sizing.day1UsableMWh)} deliverable on day one (${pc(sizing.day1UsableMWh / sizing.installedDcMWh)} of nameplate)`);
      w(`- ${sizing.systemCRate.toFixed(3)} C discharge, ${sizing.chargeCRate.toFixed(3)} C charge, against ${sizing.packCRate.toFixed(2)} C the pack sustains`);
      w(`- ${pc(sizing.rteAc)} round trip at the connection · ${sizing.recoveryDurationH.toFixed(2)} h to recharge at rated power`);
      w(`- ${sizing.footprintM2.toFixed(0)} m² of enclosure footprint, ${sizing.massTonnes.toFixed(0)} t`);
      w('');
      w('### How the fleet was arrived at');
      w('');
      for (const [title, chain] of [['Energy', r.energy], ['Power', r.power]] as const) {
        w(`**${title}**`);
        w('');
        w('| Step | Figure | Why |');
        w('| --- | ---: | --- |');
        for (const st of chain) {
          const v = st.unit === 'units' ? st.value.toFixed(0) : st.unit === 'MW' ? u.powerText(st.value) : u.energyText(st.value);
          w(`| ${st.label} | **${v}** | ${st.detail} |`);
        }
        w('');
      }
      if (r.reasons.length) {
        for (const x of r.reasons) w(`- ${x.text}`);
        w('');
      }
      w('### The landed build-up, per container');
      w('');
      w('| Step | Figure |');
      w('| --- | ---: |');
      w(`| Basic price, FOB | ${landed.kWh.toLocaleString('en-IN')} kWh × $${rates.basicPriceUsdPerKWh.toFixed(0)}/kWh = $${Math.round(landed.fobUsd).toLocaleString('en-IN')} |`);
      w(`| Ocean freight, ${pb.landed.oceanFreightPct}% | $${Math.round(landed.oceanFreightUsd).toLocaleString('en-IN')} |`);
      w(`| CIF | $${Math.round(landed.cifUsd).toLocaleString('en-IN')} = ₹${Math.round(landed.cifInr).toLocaleString('en-IN')} at ₹${fx}/US$ |`);
      w(`| Customs duty, ${pb.landed.customsDutyPct}% of CIF | ₹${Math.round(landed.customsDutyInr).toLocaleString('en-IN')} |`);
      w(`| Inland clearance, ${pb.landed.inlandClearancePct}% of CIF | ₹${Math.round(landed.inlandClearanceInr).toLocaleString('en-IN')} |`);
      w(`| **Delivered, one container** | **₹${Math.round(landed.deliveredInr).toLocaleString('en-IN')}** |`);
      w(`| Power conversion, allocated | ₹${Math.round(landed.pcsInr).toLocaleString('en-IN')} |`);
      w('');
      w('### Order value');
      w('');
      costTable(w, sizing, finance);
      w('### What it is not');
      w('');
      w(`Delivered equipment at site. It excludes foundations and civil works, MV and LV switchgear, `
        + `cabling and terminations, installation, commissioning, detailed engineering and grid studies. `
        + `Those come to about **${inr((finance.indicativeInstalledUsd ?? finance.capexUsd) - finance.capexUsd)}** on `
        + `this plant, for an indicative installed cost of **${inr(finance.indicativeInstalledUsd ?? finance.capexUsd)}** `
        + `(+${Math.round(100 * ((finance.indicativeInstalledUsd ?? finance.capexUsd) / finance.capexUsd - 1))}%).`);
      w('');
      w(`It also excludes the augmentation programme: ${sizing.augmentations.length
        ? `${sizing.augmentations.length} top-up${sizing.augmentations.length === 1 ? '' : 's'} (${sizing.augmentations.map(a => `year ${a.year}: ${a.units} × ${u.energyText(a.dcMWh)}`).join('; ')}), about ${inr(finance.augmentationUsd)} across the term at the book's ${pb.batteryPriceDeclinePct}%/yr price decline`
        : 'none scheduled — the fleet carries its own twenty years'}.`);
      w('');
      w('### Rates');
      w('');
      w(`| Per kWh of nameplate | ${exact(finance.capexUsd / (sizing.installedDcMWh * 1000))} |`);
      w('| --- | ---: |');
      w(`| Per kWh contracted at the load | ${exact(finance.capexUsd / (sizing.requiredUsableMWh * 1000))} |`);
      w(`| Per kW of contracted power | ${exact(finance.capexUsd / (sizing.ratedPowerMW * 1000))} |`);
      w(`| Lifetime throughput | ${u.energyText(sizing.lifetimeThroughputMWh)} against a ${u.energyText(sizing.warrantyThroughputMWh)} warranty basis |`);
      w('');
      const raised = sizing.warnings.filter(x => x.level !== 'info');
      if (raised.length) {
        w('### Raised against this design');
        w('');
        for (const x of raised) w(`- *${x.level}* — ${x.text}`);
        w('');
      }
    }

    w('---');
    w('');
    w('Indicative. Every rate is a platform default until the organization\'s own negotiated rates '
      + 'replace them, and the degradation schedule is the supplied 20-year table — the single '
      + 'assumption with the widest published disagreement, per `docs/VALIDATION.md`.');
    w('');
    w('*Developed and managed by jouleWise Technologies · www.joulewise.com*');
    writeFileSync(join(import.meta.dirname, '..', 'docs', 'QUOTE-1MW-5MWh.md'), out.join('\n') + '\n');
    process.stdout.write('\nwrote docs/QUOTE-1MW-5MWh.md\n');
  });
});
