import { describe, it } from 'vitest';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { defaultSizingInput, sizeSystem, recoveryHours, enclosureHierarchy, retentionFromTable, suppliedRetention } from '../src/sizing/engine';
import { packOf, cellOf, enclosureEnergyKWh, enclosureCellCount } from '../src/catalog/products';
import * as u from '../src/domain/units';

/**
 * How somebody checks the studio's answer against something that is not the studio.
 *
 * `npm run verify`. Written because the right question was asked of a single sentence — "one
 * container at 1 MW gives 3.56 h at commissioning, 3.35 h after a year and 2.30 h in year twenty"
 * — and the honest answer is that the sentence is not one claim. It is six, multiplied together,
 * and each is settled by a different document by a different party. The arithmetic is the easy
 * part and nobody should be verifying that; the inputs are the entire argument.
 */
const pc = (x: number) => `${(x * 100).toFixed(2)}%`;

describe('verification pack', () => {
  it('writes how each factor is checked', () => {
    const base = defaultSizingInput('peak-shaving');
    const s = sizeSystem({
      ...base, mode: 'power-duration', powerMW: 1, durationH: 2.29, augmentation: 'none',
      equipment: 'pinned', enclosureId: 'enc-5mwh-20ft', pcsId: 'pcs-1725', transformerId: 'tx-1600',
      gridKV: 11, chargeDurationH: recoveryHours(2.29, base.losses),
    });
    const enc = s.enclosure, pack = packOf(enc), cell = cellOf(pack), L = s.input.losses;
    const nameplate = enclosureEnergyKWh(enc);
    const cells = enclosureCellCount(enc);
    const auxPerCycle = enc.auxMWhPerDayDischarge * L.auxScale / Math.max(s.input.cyclesPerDay, 1);
    const out: string[] = [];
    const w = (x = '') => out.push(x);

    w('# Verifying the duration claim');
    w('');
    w('> One container at 1 MW gives **3.56 h** at commissioning, **3.35 h** after a year and');
    w('> **2.30 h** in year twenty.');
    w('');
    w('Generated by `npm run verify` from the same engine that makes the claim.');
    w('');
    w('## That sentence is not one claim');
    w('');
    w('It is six numbers multiplied together, and each is settled by a different document produced');
    w('by a different party. Nobody should be verifying the arithmetic — it is one line and it is');
    w('in `src/sizing/engine.ts` under test. **The inputs are the entire argument.**');
    w('');
    w('```');
    w('  hours at 1 MW  =  nameplate × SOC window × depth of discharge × discharge path × retention');
    w('                    ─────────────────────────────────────────────────────────────────────── ');
    w('                                        rated power');
    w('                    less auxiliaries');
    w('```');
    w('');
    w(`With this container: **${nameplate.toLocaleString('en-IN')} kWh** × **${pc(L.usableDcWindow)}**`
      + ` × **${pc(s.input.dod)}** × **${pc(s.dischargePathEfficiency)}** × retention,`
      + ` less **${(auxPerCycle * 1000).toFixed(0)} kWh** a cycle, at **1 MW**.`);
    w('');
    w('| At | Retention | Deliverable | Hours at 1 MW |');
    w('| --- | ---: | ---: | ---: |');
    for (const [label, year] of [['Commissioning', 0], ['End of year 1', 1], ['End of year 10', 10], ['End of year 20', 20]] as const) {
      const r = retentionFromTable(year, suppliedRetention);
      const mwh = year === 0 ? s.day1UsableMWh : (s.years[year]?.usableMWh ?? 0);
      w(`| ${label} | ${pc(r)} | ${u.energyText(mwh)} | ${mwh.toFixed(2)} h |`);
    }
    w('');
    w('## The six factors, and who settles each');
    w('');
    w('| # | Factor | Figure used | Where it comes from now | Who settles it | The document to demand |');
    w('| --- | --- | ---: | --- | --- | --- |');
    const rows: [string, string, string, string, string][] = [
      ['Nameplate energy',
        `${nameplate.toLocaleString('en-IN')} kWh`,
        `Computed: ${cells.toLocaleString('en-IN')} cells × ${cell.nominalV} V × ${cell.ah} Ah. Cell marked \`${cell.provenance}\`.`,
        'The cell maker, then the integrator',
        'Cell data sheet (nominal voltage, rated capacity and the rate it is rated at) **and** the container bill of materials, so the cell count can be multiplied out. Capacity per **IEC 62620**.'],
      ['Usable state-of-charge window',
        pc(L.usableDcWindow),
        'Platform default, editable per project.',
        'The BMS configuration, which is the integrator',
        'The BMS parameter sheet, or the supplier\'s written statement of *usable* energy against *nameplate*. This is a setting, not a property — it can be read off a commissioned system.'],
      ['Depth of discharge',
        pc(s.input.dod),
        'An operating choice carried from the application preset.',
        'Whoever writes the contract',
        'Nothing. It is a decision, and it belongs in the performance annexure beside the warranty it interacts with.'],
      ['Discharge path efficiency',
        pc(s.dischargePathEfficiency),
        `DC cable ${pc(L.dcCableLoss)} + converter ${pc(L.pcsLoss)} + AC cable ${pc(L.acCableLoss)}${s.transformer ? ` + transformer ${pc(L.idtLoss)}` : ''}, all platform defaults.`,
        'The converter and transformer makers, plus the cable design',
        'Converter efficiency curve measured per **IEC 61683** (weighted figures usually quoted per **EN 50530**, EU or CEC weighting) · transformer routine test report per **IEC 60076-1**, no-load and load loss · the cable sizing calculation for the run actually installed.'],
      ['Auxiliary consumption',
        `${(auxPerCycle * 1000).toFixed(0)} kWh a cycle`,
        `${enc.auxMWhPerDayDischarge * 1000} kWh a day, ${enc.cooling}-cooled, marked \`${enc.provenance}\`.`,
        'The integrator — and it is the number most often left out',
        'The thermal management rating and a heat-balance calculation at the site\'s design ambient. **Ask explicitly whether the quoted round-trip efficiency is measured inside or outside the auxiliaries**; the answer moves it by several points.'],
      ['Capacity retention',
        `${pc(retentionFromTable(20, suppliedRetention))} at year 20`,
        `The supplied 20-year schedule (\`${s.input.degradation.mode}\` basis).`,
        'Nobody can measure it in advance — the warranty settles it',
        'The supplier\'s guaranteed capacity curve, year by year, with its conditions: cycles a year, depth, temperature, and what happens if it is missed. Cycle-life evidence per **IEC 61427-2** (on-grid endurance, which also measures round-trip efficiency before, during and after) or **IEC 62620**.'],
    ];
    rows.forEach((r, i) => w(`| ${i + 1} | ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]} | ${r[4]} |`));
    w('');
    w('## Then stop verifying factors and measure the result');
    w('');
    w('Five of the six can be checked on paper before anything is bought. The sixth cannot: nobody');
    w('has a twenty-year measurement of a cell that has been in production for three years, and any');
    w('supplier who offers one is extrapolating. **Retention is not verified, it is warranted** — so');
    w('the thing to negotiate is the guarantee and its remedy, not the curve.');
    w('');
    w('For everything else the authority is a measurement of the assembled system, not a');
    w('recalculation of its parts:');
    w('');
    w('| Test | Standard | What it settles | When |');
    w('| --- | --- | --- | --- |');
    w('| Rated energy and rated power at the system boundary | **IEC 62933-2-1** — *Electrical energy storage (EES) systems, Part 2-1: unit parameters and testing methods* | Factors 1–5 together, as one measured number. A discharge at the declared rate from the declared upper limit to the declared lower one. | Factory acceptance, then site acceptance |');
    w('| Round-trip efficiency | **IEC 62933-2-1**, or the DOE-OE protocol **PNNL-22010 Rev 2 / SAND2016-3078** for duty-cycle-based figures | Factor 4 and factor 5 together, at the boundary you agreed | Site acceptance |');
    w('| Capacity test, repeated annually | The same procedure as at handover, written into the contract | Factor 6, as it actually happens | Every year of the warranty |');
    w('');
    w('## Tolerances, which are generous unless you tighten them');
    w('');
    w('A verified figure is a figure plus the band it was allowed to miss by, and the default bands');
    w('in the standards are wider than most buyers assume. Two worth naming in the contract rather');
    w('than inheriting:');
    w('');
    w('- **Transformer losses.** IEC 60076 conventionally allows the measured loss to exceed the');
    w('  guaranteed value by up to **+15%** unless the contract says otherwise. On the transformer in');
    w('  this design that is the difference between a stated figure and one that is materially worse,');
    w('  every hour of every year. State the guaranteed no-load and load loss *and* the tolerance.');
    w('- **Capacity.** The measurement is only as good as its conditions. A capacity test is');
    w('  meaningless unless the rate, the ambient, the state-of-charge limits and the rest period');
    w('  before it are all fixed in the same document as the number.');
    w('');
    w('Write the guaranteed value, the test that measures it, the conditions it is measured under and');
    w('the tolerance, together, in one annexure. Any one of the four missing makes the other three');
    w('unenforceable.');
    w('');
    w('## The thing that makes two honest parties disagree');
    w('');
    w('**The measurement boundary.** Every figure above changes depending on where it is measured');
    w('and what is inside the fence:');
    w('');
    w('- **DC terminals or AC terminals?** The converter is worth several points.');
    w('- **Before or after the transformer?** Another point, and it is the customer\'s point.');
    w('- **Auxiliaries inside or outside?** On a liquid-cooled container in a hot climate this is the');
    w('  largest single term after the cells, and it is the one most often quietly excluded.');
    w('- **At what rate, and at what ambient?** Capacity measured at 0.2 C and 25 °C is not the');
    w('  capacity available at 0.5 C and 45 °C.');
    w('');
    w('Agree the boundary in writing before anybody tests anything. Two parties measuring the same');
    w('container at different boundaries will both be right and will not agree, and that argument is');
    w('more expensive than the test.');
    w('');
    w('## What this studio already does for you');
    w('');
    w('- Every figure states its own provenance: `supplied` from a document, `indicative` as a');
    w('  platform default, `assumed` where it was reconciled and needs confirming.');
    w(`- The plant in this pack is **${s.units} × ${enclosureHierarchy(enc)}**, so a label can be checked against a bill of materials.`);
    w('- `docs/SIZING-AUDIT.md` shows the derivation for ten sizes, line by line, for checking by hand.');
    w('- `docs/VALIDATION.md` puts the same cases through NREL SAM. Deliverable energy agrees within');
    w('  about 3%, the studio reading low. On retention SAM\'s own three lifetime models disagree with');
    w('  each other by twenty points at year twenty — which is the evidence for the paragraph above');
    w('  about warranting rather than verifying.');
    w('');
    w('---');
    w('');
    w('*Developed and managed by jouleWise Technologies · www.joulewise.com*');
    writeFileSync(join(import.meta.dirname, '..', 'docs', 'VERIFICATION.md'), out.join('\n') + '\n');
    process.stdout.write('\nwrote docs/VERIFICATION.md\n');
  });
});
